In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
df_oecd = pd.read_csv( "oecd_bli_2015.csv", thousands= ',')
df_gdp = pd.read_csv( "gdp_per_capita.csv", thousands= ',',delimiter="\t",encoding="latin1",na_values="n/a")

In [26]:
df_oecd

Country  \
0                                          Afghanistan   
1                                              Albania   
2                                              Algeria   
3                                               Angola   
4                                  Antigua and Barbuda   
..                                                 ...   
185                                            Vietnam   
186                                              Yemen   
187                                             Zambia   
188                                           Zimbabwe   
189  International Monetary Fund, World Economic Ou...   

                                    Subject Descriptor         Units  Scale  \
0    Gross domestic product per capita, current prices  U.S. dollars  Units   
1    Gross domestic product per capita, current prices  U.S. dollars  Units   
2    Gross domestic product per capita, current prices  U.S. dollars  Units   
3    Gross domestic product per capita, current prices  U.S. dollars  Units   
4    Gross domestic product per capita, current prices  U.S. dollars  Units   
..                                                 ...           ...    ...   
185  Gross domestic product per capita, current prices  U.S. dollars  Units   
186  Gross domestic product per capita, current prices  U.S. dollars  Units   
187  Gross domestic product per capita, current prices  U.S. dollars  Units   
188  Gross domestic product per capita, current prices  U.S. dollars  Units   
189                                                NaN           NaN    NaN   

                         Country/Series-specific Notes       2015  \
0    See notes for:  Gross domestic product, curren...    599.994   
1    See notes for:  Gross domestic product, curren...   3995.383   
2    See notes for:  Gross domestic product, curren...   4318.135   
3    See notes for:  Gross domestic product, curren...   4100.315   
4    See notes for:  Gross domestic product, curren...  14414.302   
..                                                 ...        ...   
185  See notes for:  Gross domestic product, curren...   2088.344   
186  See notes for:  Gross domestic product, curren...   1302.940   
187  See notes for:  Gross domestic product, curren...   1350.151   
188  See notes for:  Gross domestic product, curren...   1064.350   
189                                                NaN        NaN   

     Estimates Start After  
0                   2013.0  
1                   2010.0  
2                   2014.0  
3                   2014.0  
4                   2011.0  
..                     ...  
185                 2012.0  
186                 2008.0  
187                 2010.0  
188                 2012.0  
189                    NaN  

[190 rows x 7 columns]

In [66]:
df_oecd.info()
u=df_oecd["Value"].unique()
u

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3292 entries, 0 to 3291
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   LOCATION               3292 non-null   object 
 1   Country                3292 non-null   object 
 2   INDICATOR              3292 non-null   object 
 3   Indicator              3292 non-null   object 
 4   MEASURE                3292 non-null   object 
 5   Measure                3292 non-null   object 
 6   INEQUALITY             3292 non-null   object 
 7   Inequality             3292 non-null   object 
 8   Unit Code              3292 non-null   object 
 9   Unit                   3292 non-null   object 
 10  PowerCode Code         3292 non-null   int64  
 11  PowerCode              3292 non-null   object 
 12  Reference Period Code  0 non-null      float64
 13  Reference Period       0 non-null      float64
 14  Value                  3292 non-null   float64
 15  Flag

array([ 1.1 ,  1.  ,  2.  , ..., 14.16, 14.24, 14.74])

In [64]:
df_gdp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 190 entries, Afghanistan to International Monetary Fund, World Economic Outlook Database, April 2016
Data columns (total 6 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Subject Descriptor             189 non-null    object 
 1   Units                          189 non-null    object 
 2   Scale                          189 non-null    object 
 3   Country/Series-specific Notes  188 non-null    object 
 4   GDP per capita                 187 non-null    float64
 5   Estimates Start After          188 non-null    float64
dtypes: float64(2), object(4)
memory usage: 14.5+ KB


In [45]:
df_gdp

Subject Descriptor  \
Country                                                                                                 
Afghanistan                                         Gross domestic product per capita, current prices   
Albania                                             Gross domestic product per capita, current prices   
Algeria                                             Gross domestic product per capita, current prices   
Angola                                              Gross domestic product per capita, current prices   
Antigua and Barbuda                                 Gross domestic product per capita, current prices   
...                                                                                               ...   
Vietnam                                             Gross domestic product per capita, current prices   
Yemen                                               Gross domestic product per capita, current prices   
Zambia                                              Gross domestic product per capita, current prices   
Zimbabwe                                            Gross domestic product per capita, current prices   
International Monetary Fund, World Economic Out...                                                NaN   

                                                           Units  Scale  \
Country                                                                   
Afghanistan                                         U.S. dollars  Units   
Albania                                             U.S. dollars  Units   
Algeria                                             U.S. dollars  Units   
Angola                                              U.S. dollars  Units   
Antigua and Barbuda                                 U.S. dollars  Units   
...                                                          ...    ...   
Vietnam                                             U.S. dollars  Units   
Yemen                                               U.S. dollars  Units   
Zambia                                              U.S. dollars  Units   
Zimbabwe                                            U.S. dollars  Units   
International Monetary Fund, World Economic Out...           NaN    NaN   

                                                                        Country/Series-specific Notes  \
Country                                                                                                 
Afghanistan                                         See notes for:  Gross domestic product, curren...   
Albania                                             See notes for:  Gross domestic product, curren...   
Algeria                                             See notes for:  Gross domestic product, curren...   
Angola                                              See notes for:  Gross domestic product, curren...   
Antigua and Barbuda                                 See notes for:  Gross domestic product, curren...   
...                                                                                               ...   
Vietnam                                             See notes for:  Gross domestic product, curren...   
Yemen                                               See notes for:  Gross domestic product, curren...   
Zambia                                              See notes for:  Gross domestic product, curren...   
Zimbabwe                                            See notes for:  Gross domestic product, curren...   
International Monetary Fund, World Economic Out...                                                NaN   

                                                    GDP per capita  \
Country                                                              
Afghanistan                                                599.994   
Albania                                                   3995.383   
Algeria                                                   4318.135   
Angola                   

In [30]:
# preparation des données 
def prepare_country_stats(oecd_bli, gdp_per_capita):
    oecd_bli = oecd_bli[oecd_bli["INEQUALITY"]=="TOT"]
    oecd_bli = oecd_bli.pivot(index="Country", columns="Indicator", values="Value")
    gdp_per_capita.rename(columns={"2015": "GDP per capita"}, inplace=True)
    gdp_per_capita.set_index("Country", inplace=True)
    full_country_stats = pd.merge(left=oecd_bli, right=gdp_per_capita
                                  ,left_index=True, right_index=True)
    full_country_stats.sort_values(by="GDP per capita", inplace=True)
    remove_indices = [0, 1, 6, 8, 33, 34, 35]
    keep_indices = list(set(range(36)) - set(remove_indices))
    return full_country_stats[["GDP per capita", 'Life satisfaction']].iloc[keep_indices]

In [31]:
country_df=prepare_country_stats(df_oecd, df_gdp)
country_df

GDP per capita  Life satisfaction
Country                                           
Russia                 9054.914                6.0
Turkey                 9437.372                5.6
Hungary               12239.894                4.9
Poland                12495.334                5.8
Slovak Republic       15991.736                6.1
Estonia               17288.083                5.6
Greece                18064.288                4.8
Portugal              19121.592                5.1
Slovenia              20732.482                5.7
Spain                 25864.721                6.5
Korea                 27195.197                5.8
Italy                 29866.581                6.0
Japan                 32485.545                5.9
Israel                35343.336                7.4
New Zealand           37044.891                7.3
France                37675.006                6.5
Belgium               40106.632                6.9
Germany               40996.511                7.0
Finland               41973.988                7.4
Canada                43331.961                7.3
Netherlands           43603.115                7.3
Austria               43724.031                6.9
United Kingdom        43770.688                6.8
Sweden                49866.266                7.2
Iceland               50854.583                7.5
Australia             50961.865                7.3
Ireland               51350.744                7.0
Denmark               52114.165                7.5
United States         55805.204                7.2

In [39]:
#Y = x + b
Y= np.c_[country_df["GDP per capita"]]# crée une liste (ou arrêt)
x= np.c_[country_df["Life satisfaction"]]
Y

array([[ 9054.914],
       [ 9437.372],
       [12239.894],
       [12495.334],
       [15991.736],
       [17288.083],
       [18064.288],
       [19121.592],
       [20732.482],
       [25864.721],
       [27195.197],
       [29866.581],
       [32485.545],
       [35343.336],
       [37044.891],
       [37675.006],
       [40106.632],
       [40996.511],
       [41973.988],
       [43331.961],
       [43603.115],
       [43724.031],
       [43770.688],
       [49866.266],
       [50854.583],
       [50961.865],
       [51350.744],
       [52114.165],
       [55805.204]])

In [38]:
x

array([[6. ],
       [5.6],
       [4.9],
       [5.8],
       [6.1],
       [5.6],
       [4.8],
       [5.1],
       [5.7],
       [6.5],
       [5.8],
       [6. ],
       [5.9],
       [7.4],
       [7.3],
       [6.5],
       [6.9],
       [7. ],
       [7.4],
       [7.3],
       [7.3],
       [6.9],
       [6.8],
       [7.2],
       [7.5],
       [7.3],
       [7. ],
       [7.5],
       [7.2]])